# Python Homework (NumPy, Pandas)

<br>

1. What does Pandas stand for?
    - Panel Data or Python Data Analysis
2. What are the 2 collections used in Pandas?
    - Series and DataFrames
3. Name 4 things Pandas can do for us.
    - Data Fill
    - Merges and Joins
    - Statistical Analysis
    - Loading and Saving Data    
4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
    - inplace=True
5. What is a CSV?
    - comma separated values file
    - CSV files contains plain text and is a well know format that can be read by everyone including Pandas.
6. When cleaning data what values do we not like in our data?
    - Null Values (use '.fillna()')

7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()`

In [14]:
import numpy as np
array1 = np.arange(12).reshape(2, 3, 2)
print(array1)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


8. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20

In [22]:
array2 = np.linspace(0, 20, 6)
print(array2)


[ 0.  4.  8. 12. 16. 20.]


9. Make a Deep Copy of the above array

In [27]:
import copy
array3 = copy.deepcopy(array2)

10. Concatenate these 3 arrays into a new array named 'newArray'...
    ```python
            ([[25, 16]])
            ([[11, 2], [13, 4]])
            ([[7, 81], [5, 6], [11, 12]])
    ```

In [64]:
a = np.array([[25, 16]])
b = np.array([[11, 2], [13, 4]])
c = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((a, b, c), axis=0)
print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


11. Sort 'newArray' in order into 'sortedArray'

In [106]:
sortedArray = np.sort(newArray, axis=0)
print(sortedArray)

[[ 5  2]
 [ 7  4]
 [11  6]
 [11 12]
 [13 16]
 [25 81]]


12. Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.

In [107]:
a, b, c, d, e, f = sortedArray
print('a = ', a, b)
print('c = ', c, d)
print('e = ', e)
print('f = ', f)

a =  [5 2] [7 4]
c =  [11  6] [11 12]
e =  [13 16]
f =  [25 81]


13. Combined and sort the following arrays into one called 'comboArray' ...

    ```python
        one = ([10, 11, 12, 13, 14, 15, 16, 17])
        two = ([20, 21, 22, 23, 24, 25, 26, 27])
        three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
    ```

In [4]:
import numpy as np
a = np.array([10, 11, 12, 13, 14, 15, 16, 17])
b = np.array([20, 21, 22, 23, 24, 25, 26, 27])
c = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((a, b, c))
comboArray = np.sort(comboArray)
print(comboArray)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


14. Take 'comboArray' and perform the following slicing activities:
    - print sec1 - the 2nd element
    - print sec2 - all elements from the 3rd element to the last
    - print sec3 - all elements from the 4th to the 14th elements
    - print sec4 - the last 6 elements
    - print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
    - print sec6 - from #20 every even element to the end
    - print sec7 - from the last element moving forward, every 5th element.

In [11]:
print(comboArray[1])
print(comboArray[2::])
print(comboArray[3:14])
print(comboArray[-6:])
print(comboArray[:-11])
print(comboArray[-8::2])
print(comboArray[::-5])


1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14]
[20 22 24 26]
[27 22 15 10  3]


## **sec7** ABOVE should read "Backward" Correct?

In [ ]:
15. Using `Series`, create a `DataFrame` that looks like this:

    | Ingredients | Quantity | Unit |
    |----|----|----|
    | Flour | 4 | cups |
    | Milk | 1 | cup |
    | Eggs | 2 | large |
    | Spam | 1 | can |

    Name: Dinner, dtype: object

In [ ]:
ing = pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'])
qty = pd.Series([4,1,2,1])
unt = pd.Series(['cups', 'cup', 'large', 'can'])

df = pd.DataFrame({'Ingredients': ing, 'Quantity': qty, 'Unit': unt})
df.name = 'Recipe'
df

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


16. Take this data and create a DataFrame named studentData
    ```Python
        {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
    ```

In [145]:
data = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
df = pd.DataFrame(data)
df.name = 'studentData'
df

Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

17. Add a new column to the DataFrame with the following deserts:
       17. Add a new column to the DataFrame with the following deserts:
        ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

In [148]:
df['Food'] = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
df

Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

           Food  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa

18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

In [155]:
df.sort_values(by = ['Name', 'address'],
                ascending = True)

Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

           Food  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge

19. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:

    ```python
        df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
    ```

In [162]:
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv(r'df.csv')

20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

In [171]:
vegs = ['brocolli', 'onion', 'garlic']
df = pd.DataFrame(vegs)
df.to_csv(r'df2.csv')


In [202]:
df = pd.read_csv(r'df2.csv')
df.sort_values
df.to_csv(r'df3.csv')